package main

// Generated by Nix from programs.lazytmux.splash.*. Committed defaults here are
// overwritten at build time. Do not rely on editing this file directly.

var splashTips = []tip{
	{Key: "prefix + s", Label: "Sessions"},
	{Key: "prefix + w", Label: "Windows"},
	{Key: "prefix + a", Label: "Claude windows"},
	{Key: "prefix + i", Label: "Issues / PRs"},
	{Key: "prefix + g", Label: "LazyGit"},
	{Key: "prefix + b", Label: "btop"},
	{Key: "prefix + R", Label: "Restore snapshot"},
	{Key: "prefix + u", Label: "Undo close"},
}

var splashPrefix = "`"

var splashTimeoutSec = 10
