{
  pkgs,
  lib,
  processIcons,
  fallbackIcon,
  maxIconsPicker,
}: let
  # Generate Go source with icon map and claude constants from Nix
  iconsGo = pkgs.writeText "icons_generated.go" ''
    package main

    // Generated by Nix from process-icons.nix and lib-claude.sh constants.
    // Do not edit manually.

    var iconMap = map[string]string{
    ${lib.concatStringsSep "\n" (lib.mapAttrsToList (k: v: "	${builtins.toJSON k}: ${builtins.toJSON v},") processIcons)}
    }

    var fallbackIcon = ${builtins.toJSON fallbackIcon}
    var maxIconsPicker = ${maxIconsPicker}

    // Claude status icons (from lib-claude.sh)
    var claudeSpinnerFrames = []string{"󰪞", "󰪟", "󰪠", "󰪡", "󰪢", "󰪣", "󰪤", "󰪥"}
    var claudeIconWaiting = "󰔟"
    var claudeIconCompacting = "󰡍"
    var claudeIconDone = "󰸞"
    var claudeIconIdle = "󰒲"
    var claudeIconError = "󰅚"
    var claudeIconDenied = "󰔟" // same clock as waiting, different color

    // Default icons (overridden by env vars or tmux options at runtime)
    var iconSession = ""
    var iconDir = ""
    var iconBranch = ""
  '';

  # Combine Go source with generated icons file
  src = pkgs.runCommand "picker-src" {} ''
    cp -r ${lib.cleanSource ./.} $out
    chmod -R u+w $out
    cp ${iconsGo} $out/icons_generated.go
    rm -f $out/default.nix
  '';
in
  pkgs.buildGoModule {
    pname = "tmux-picker-generate";
    version = "0.1.0";
    inherit src;
    vendorHash = "sha256-gGs19TTxci8a3adA4CJOKs/IHDhqojjpxH9WueDInLk=";
    ldflags = ["-s" "-w"]; # strip debug info for smaller binary + faster startup
    # Binary name matches pname (Go module produces "picker" by default)
    postInstall = ''
      mv $out/bin/picker $out/bin/tmux-picker-generate
    '';
  }
