# cSpell:disable
config:
  fallback-icon: "?"
  show-name: true
  always-show-fallback-name: false

icons:
  zig: "↯"
  ruby: ""
  java: ""
  gcloud: ""
  gulp: ""
  grunt: ""
  clang: ""
  gcc: ""
  cmake: ""
  julia: ""
  make: ""
  go: ""
  tsc: ""
  lvim: ""
  vi: ""
  vim: ""
  elixir: ""
  jekyll: ""
  emacs: ""
  bazel: ""
  nvim: ""
  git: ""
  gitui: ""
  lazygit: ""
  tig: ""
  bitbucket: ""
  mysql: ""
  gh: ""
  gitlab: ""
  wordpress: ""
  visualstudio: ""
  babel: ""
  gping: ""
  ping: ""
  node: ""
  yarn: ""
  npm: ""
  jj: ""
  lazyjj: ""
  svn: ""
  hg: ""
  virtualbox: ""
  scala: ""
  pip: ""
  pip3: ""
  Python: ""
  python: ""
  python3: ""
  php: ""
  laravel: ""
  heroku: ""
  jest: ""
  ng: ""
  swift: ""
  ant: ""
  atom: ""
  jenkins: ""
  netbeans: ""
  perl: ""
  redis: ""
  psql: ""
  webpack: ""
  ghc: ""
  stack: ""
  apt: ""
  dpkg: ""
  nala: ""
  travis: ""
  dotnet: ""
  composer: ""
  firebase: ""
  bash: ""
  fish: ""
  just: ""
  nu: ""
  tcsh: ""
  zsh: ""
  code: ""
  code-insiders: ""
  dart: ""
  flutter: ""
  mocha: ""
  mongo: ""
  cargo: ""
  rustc: ""
  rustup: ""
  gradle: ""
  sublime_text: ""
  csharp: ""
  eclipse: ""
  beam: ""
  beam.smp: ""
  maven: ""
  clion: ""
  idea: ""
  pycharm: ""
  react: ""
  brew: ""
  yazi: ""
  deno: ""
  btm: ""
  btop: ""
  glances: ""
  htop: ""
  mactop: ""
  top: ""
  powershell: ""
  screen: ""
  tmux: ""
  tickrs: ""
  ghostty: ""
  curl: ""
  wget: ""
  rsync: ""
  openssl: ""
  nano: ""
  crontab: ""
  lf: ""
  lfcd: ""
  ranger: ""
  gpg: ""
  systemctl: ""
  cfdisk: ""
  fdisk: ""
  parted: ""
  apache2: ""
  httpd: ""
  nginx: ""
  caffeinate: ""
  alacritty: ""
  gnome-terminal: ""
  iterm2: ""
  sudo: ""
  gdb: ""
  lldb: ""
  valgrind: ""
  sqlite: ""
  unzip: ""
  zip: ""
  aws: ""
  vagrant: ""
  pacman: ""
  paru: ""
  yay: ""
  docker: ""
  lazydocker: ""
  dnf: ""
  yum: ""
  doctl: ""
  puppet: ""
  ansible: ""
  terraform: "ﲽ"
  R: "ﳒ"
  vue: "﵂"
  hx: "󰔤"
  topgrade: "󰚰"
  console: "󰞷"
  scp: "󰣀"
  ssh: "󰣀"
  bat: "󰭟"
  weechat: "󰭹"
  helm: "󱃾"
  k9s: "󱃾"
  kubectl: "󱃾"
  kubie: "󱃾"
  minikube: "󱃾"
  unicorn: "󱗃"
