#!/usr/bin/env bash
# Returns up to 3 unique process icons for a tmux window's panes.
# Usage: tmux-window-icons <session_name> <window_index>
# Output: emoji icons joined, e.g. "🧠🐟" or "🧠❄️🐟"
#
# The icon map below is generated by Nix — edit processIcons in tmux.conf.nix, not here.

set -euo pipefail

# shellcheck disable=SC2190  # @ICON_MAP@ is a Nix placeholder, substituted at build time
declare -A ICON_MAP=(
	@ICON_MAP@
)
FALLBACK="@FALLBACK_ICON@"
MAX_ICONS=3

session="$1"
window="$2"

# Collect unique process names preserving first-seen order
declare -A seen
declare -a unique_procs
while IFS= read -r proc; do
	[[ -z $proc ]] && continue
	if [[ -z ${seen[$proc]+x} ]]; then
		seen[$proc]=1
		unique_procs+=("$proc")
	fi
done < <(tmux list-panes -t "${session}:${window}" -F '#{pane_current_command}' 2>/dev/null)

# Map to icons, cap at MAX_ICONS
result=""
count=0
for proc in "${unique_procs[@]}"; do
	((count >= MAX_ICONS)) && break
	icon="${ICON_MAP[$proc]:-$FALLBACK}"
	result+="$icon"
	((count++))
done

echo "$result"
